export { Db, createPool, type Queryable, type TenantClient } from "./client.js";
export { assertRlsEnforced, RlsBypassError } from "./guard.js";
export {
  activatePendingTotp,
  authenticateApiKey,
  authenticateSession,
  createApiKey,
  createSession,
  applyPasswordReset,
  claimPasswordReset,
  claimRecoveryCode,
  consumeTotp,
  countUnusedRecoveryCodes,
  discardPendingTotp,
  getAccountUser,
  getPendingTotp,
  createUser,
  findPasswordReset,
  findUserForLogin,
  issuePasswordReset,
  listApiKeys,
  recordLoginAttempt,
  replaceRecoveryCodes,
  revokeApiKey,
  setPendingTotp,
  revokeAllSessions,
  revokeSession,
  revokeSessionsForUser,
  setTotpSecret,
  touchSession,
  type ApiKeyRow,
  type AuthenticatedKey,
  type AuthenticatedSession,
  type CreateApiKeyInput,
  type CreateSessionInput,
  type CreateUserInput,
  type LoginCandidate,
  type ResetClaim,
} from "./auth.js";
export {
  claimInboundMessage,
  finishInboundMessage,
  resolveInbox,
  type ClaimInput,
  type ResolvedInbox,
} from "./inbound.js";
export { MIGRATIONS_DIR, migrate, type AppliedMigration } from "./migrate.js";
export {
  countByStatus,
  countDocuments,
  getDocument,
  getFindings,
  insertDocument,
  insertFindings,
  listDocuments,
  listBelegeForBundle,
  listDocumentsForExport,
  type DocumentListItem,
  type DocumentRow,
  type BelegRow,
  type ExportRow,
  type FindingRow,
  type InsertDocumentInput,
  type InsertFindingInput,
  type ListFilters,
  type StatusCount,
} from "./documents.js";
export {
  createTenant,
  getInboxAddress,
  getTenant,
  type CreatedTenant,
  type CreateTenantInput,
  type TenantRow,
} from "./tenants.js";
export {
  archiveDocument,
  chainLinks,
  entriesForDay,
  linkForDay,
  proofForDocument,
  sealArchiveDay,
  utcDay,
  type ArchiveProof,
} from "./archive-store.js";
export {
  getDokuHtml,
  insertDoku,
  latestDoku,
  listDoku,
  verifyDokuChain,
  type DokuVersionRow,
  type StoreDokuInput,
} from "./verfahrensdoku-store.js";
export {
  parseAmount,
  searchDocuments,
  type SearchHit,
  type SearchMode,
  type SearchQuery,
  type SearchResult,
} from "./search.js";
