export { Db, createPool, type Queryable, type TenantClient } from "./client.js";
export { assertRlsEnforced, RlsBypassError } from "./guard.js";
export {
  authenticateApiKey,
  authenticateSession,
  createApiKey,
  createSession,
  applyPasswordReset,
  claimPasswordReset,
  consumeTotp,
  createUser,
  findPasswordReset,
  findUserForLogin,
  issuePasswordReset,
  recordLoginAttempt,
  revokeAllSessions,
  revokeSession,
  revokeSessionsForUser,
  setTotpSecret,
  touchSession,
  type AuthenticatedKey,
  type AuthenticatedSession,
  type CreateApiKeyInput,
  type CreateSessionInput,
  type CreateUserInput,
  type LoginCandidate,
  type ResetClaim,
} from "./auth.js";
export {
  claimInboundMessage,
  finishInboundMessage,
  resolveInbox,
  type ClaimInput,
  type ResolvedInbox,
} from "./inbound.js";
export { MIGRATIONS_DIR, migrate, type AppliedMigration } from "./migrate.js";
export {
  countByStatus,
  countDocuments,
  getDocument,
  getFindings,
  insertDocument,
  insertFindings,
  listDocuments,
  type DocumentListItem,
  type DocumentRow,
  type FindingRow,
  type InsertDocumentInput,
  type InsertFindingInput,
  type ListFilters,
  type StatusCount,
} from "./documents.js";
export {
  createTenant,
  getInboxAddress,
  getTenant,
  type CreatedTenant,
  type CreateTenantInput,
  type TenantRow,
} from "./tenants.js";
export {
  archiveDocument,
  chainLinks,
  entriesForDay,
  linkForDay,
  proofForDocument,
  sealArchiveDay,
  utcDay,
  type ArchiveProof,
} from "./archive-store.js";
